steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:latest'
    dir: 'terraform'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
      echo "**************************"
      echo "******TERRAFORM INIT******"
      echo "**************************"
      terraform init
  - id: 'tf plan'
    name: 'hashicorp/terraform:latest'
    dir: 'terraform'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
      echo "**************************"
      echo "******TERRAFORM PLAN******"
      echo "**************************"
      terraform plan
  - id: 'tf apply'
    name: 'hashicorp/terraform:latest'
    dir: 'terraform'
    entrypoint: 'sh'
    args: 
      - '-c'
      - | 
        echo "**************************"
        echo "******TERRAFORM APPLY******"
        echo "**************************"
        terraform apply -auto-approve
options:
  logging: CLOUD_LOGGING_ONLY